### ISSUE TITLE
Tamarinne Again

### ISSUE THREAD

**Issue by Cayde0620** [Zarroc2762/E7-Gear-Optimizer#33] opened 2019-09-27 18:48 UTC
Unable to add Tamarinme as blank hero due to this error.
![aga](https://user-images.githubusercontent.com/44105293/65794296-65c2f700-e19a-11e9-925e-e336db2d9b59.JPG)

**Comment by AlexeiA** [comment] 2019-09-27 19:29
We hopefully fix this issue in the next update.
It would be helping if you try to enable caching of epicsevendb.com and add db.hero.Tamarinne.json file from the attached zip archive to the cache directory and then try to add Tamarinne again, so we could see if the upcoming change really fixes the issue.
[db.hero.Tamarinne.zip](https://github.com/Zarroc2762/E7-Gear-Optimizer/files/3664265/db.hero.Tamarinne.zip)

**Comment by Zarroc2762** [comment] 2019-10-06 15:01
Sorry for not getting back to you sooner. Work keeps me pretty buse at the moment. 
A user on reddit found a workaround for that problem. In Windows 10 you can go to Settings > Time & Language > Language (tab on the left side) > administrative language settings (under related settings on the right side) and set Language for non-Unicode Programs to English (United States). Be aware though that this might cause issues with other applications.

I'm currently looking into why windows is detecting the optimizer as non unicode. @AlexeiA Do you have any idea? Winforms and the JSON.NET package support Unicode so it should be possible to fix this. It seems like we are missing some sort of setting or something?

**Comment by Zarroc2762** [comment] 2019-10-06 15:18
Please check if the problem is resolved with the latest version

**Closed** 2019-10-28 19:47 UTC
