### ISSUE TITLE
Strange Optimizer Error

### ISSUE THREAD

**Issue by jdegasperi** [Zarroc2762/E7-Gear-Optimizer#19] opened 2019-09-05 18:49 UTC
I haven't been able to determine the exact pattern to the issue, but for some reason the optimizer is not picking up my Sol's current equipment (and only happens with Sol so far).

If you see the first screenshot, accoding to the filters, his current equipment should show as a result. But it doesn't.

![image](https://user-images.githubusercontent.com/12550280/64370229-6b427c80-cff4-11e9-8f4b-dd934c842a9c.png)

If I just click the "Keep currently equipped items" checkbox and hit optimize again without modifying any other filters, then the exact equipped setup shows in the list.

![image](https://user-images.githubusercontent.com/12550280/64370261-7d241f80-cff4-11e9-8146-ba21a8864be1.png)

It doesn't matter if the equipment is locked or not, or if I click the "locked items" checkbox or not. The issue persists. And again, so far it's only with this character. I can provide the json if needed.

**Comment by Zarroc2762** [comment] 2019-09-17 16:59
I was not able to recreate this problem with my own equipment. Please provide your JSON file.

**Comment by jdegasperi** [comment] 2019-09-19 15:03
I stepped on my backup file for the issue by mistake, but in this JSON you will see the gear shows up but with 4% extra crit (see new screenshot).
[E7 Gear Optimizer.zip](https://github.com/Zarroc2762/E7-Gear-Optimizer/files/3631915/E7.Gear.Optimizer.zip)
![image](https://user-images.githubusercontent.com/12550280/65256136-6a6e1800-dad5-11e9-9c18-0b0629da3277.png)

**Comment by Zarroc2762** [comment] 2019-09-19 15:18
No Problem. I'll close the issue for the time being. Just reopen it if you encounter the error again.

**Closed by Zarroc2762** 2019-09-19 15:18 UTC

**Comment by Zarroc2762** [comment] 2019-09-19 17:59
The 4 % extra crit is not a bug. Current Gear shows the stats your 
character will have ingame. Crit ist capped at 100% ingame. Results show 
the actual sum of the stats on your gear. This means you can see how 
much crit is wasted because its above the cap.

Am 19.09.2019 um 17:03 schrieb Javier Degasperi:
